<?php

namespace craft\cloud\composer;

use Composer\Composer;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;
use Composer\Script\ScriptEvents;

class ComposerPlugin implements PluginInterface, EventSubscriberInterface
{
    private Composer $composer;
    private IOInterface $io;

    public static function getSubscribedEvents(): array
    {
        return [
            ScriptEvents::POST_AUTOLOAD_DUMP => 'injectPreload',
        ];
    }

    public function activate(Composer $composer, IOInterface $io): void
    {
        $this->composer = $composer;
        $this->io = $io;
    }

    public function deactivate(Composer $composer, IOInterface $io): void
    {
    }

    public function uninstall(Composer $composer, IOInterface $io): void
    {
    }

    public function injectPreload(): void
    {
        $package = $this->composer->getRepositoryManager()
            ->getLocalRepository()
            ->findPackage('craftcms/cloud-composer', '*');

        if ($package === null) {
            return;
        }

        $installPath = $this->composer->getInstallationManager()->getInstallPath($package);
        $preloadFile = $installPath . '/preload.php';

        if (!file_exists($preloadFile)) {
            $this->io->writeError('<warning>craftcms/cloud-composer: preload.php not found</warning>');
            return;
        }

        $vendorDir = $this->composer->getConfig()->get('vendor-dir');
        $composerDir = $vendorDir . '/composer';
        $identifier = md5('craftcms/cloud-composer:preload.php');
        $preloadPath = realpath($preloadFile);

        $this->injectIntoAutoloadFiles($composerDir, $vendorDir, $identifier, $preloadPath);
        $this->injectIntoAutoloadStatic($composerDir, $vendorDir, $identifier, $preloadPath);

        $this->io->writeError('<info>craftcms/cloud-composer: preload.php injected as first autoload file.</info>');
    }

    private function injectIntoAutoloadFiles(string $composerDir, string $vendorDir, string $identifier, string $preloadPath): void
    {
        $filePath = $composerDir . '/autoload_files.php';

        if (!file_exists($filePath)) {
            return;
        }

        $files = include $filePath;

        if (!is_array($files)) {
            return;
        }

        // Remove existing entry if present (idempotent)
        unset($files[$identifier]);

        // Prepend our entry
        $files = [$identifier => $preloadPath] + $files;

        $baseDir = dirname($vendorDir);
        $content = "<?php\n\n";
        $content .= "// autoload_files.php @generated by Composer\n\n";
        $content .= "\$vendorDir = dirname(__DIR__);\n";
        $content .= "\$baseDir = dirname(\$vendorDir);\n\n";
        $content .= "return array(\n";

        foreach ($files as $hash => $path) {
            $content .= "    '" . $hash . "' => " . $this->exportPath($path, $vendorDir, $baseDir) . ",\n";
        }

        $content .= ");\n";

        file_put_contents($filePath, $content);
    }

    private function injectIntoAutoloadStatic(string $composerDir, string $vendorDir, string $identifier, string $preloadPath): void
    {
        $filePath = $composerDir . '/autoload_static.php';

        if (!file_exists($filePath)) {
            return;
        }

        $content = file_get_contents($filePath);
        $exportedPath = $this->exportStaticPath($preloadPath, $vendorDir);
        $newEntry = "        '" . $identifier . "' => " . $exportedPath . ",";

        // If $files array exists, inject/move our entry to first position
        if (preg_match('/public static \$files = array \(\n(.*?)\n    \);/s', $content, $matches)) {
            $filesBlock = $matches[1];
            $lines = array_filter(explode("\n", $filesBlock), fn($line) => trim($line) !== '');

            // Remove existing entry if present
            $lines = array_values(array_filter($lines, fn($line) => !str_contains($line, "'" . $identifier . "'")));

            // Prepend our entry
            array_unshift($lines, $newEntry);

            $newBlock = implode("\n", $lines);
            $content = preg_replace(
                '/public static \$files = array \(\n.*?\n    \);/s',
                "public static \$files = array (\n" . $newBlock . "\n    );",
                $content,
            );
        } else {
            // No $files array yet — inject one after the class opening
            $filesArray = "    public static \$files = array (\n" . $newEntry . "\n    );\n";
            $content = preg_replace(
                '/(class ComposerStaticInit[a-f0-9]+ *\{)\n/',
                "$1\n" . $filesArray,
                $content,
            );
        }

        file_put_contents($filePath, $content);
    }

    /**
     * Export a path for autoload_files.php, which declares $vendorDir and $baseDir variables.
     */
    private function exportPath(string $absolutePath, string $vendorDir, string $baseDir): string
    {
        $absolutePath = str_replace('\\', '/', $absolutePath);
        $vendorDir = str_replace('\\', '/', $vendorDir);
        $baseDir = str_replace('\\', '/', $baseDir);

        if (str_starts_with($absolutePath, $vendorDir . '/')) {
            return '$vendorDir . ' . var_export(substr($absolutePath, strlen($vendorDir)), true);
        }

        if (str_starts_with($absolutePath, $baseDir . '/')) {
            return '$baseDir . ' . var_export(substr($absolutePath, strlen($baseDir)), true);
        }

        return var_export($absolutePath, true);
    }

    /**
     * Export a path for autoload_static.php, which uses __DIR__ relative paths.
     * __DIR__ resolves to vendor/composer/, so:
     *   __DIR__ . '/..' = vendor/
     *   __DIR__ . '/../..' = project root
     */
    private function exportStaticPath(string $absolutePath, string $vendorDir): string
    {
        $absolutePath = str_replace('\\', '/', $absolutePath);
        $vendorDir = str_replace('\\', '/', $vendorDir);
        $baseDir = str_replace('\\', '/', dirname($vendorDir));

        if (str_starts_with($absolutePath, $vendorDir . '/')) {
            $relativePath = substr($absolutePath, strlen($vendorDir));
            return "__DIR__ . '/.." . "' . '" . $relativePath . "'";
        }

        if (str_starts_with($absolutePath, $baseDir . '/')) {
            $relativePath = substr($absolutePath, strlen($baseDir));
            return "__DIR__ . '/../.." . "' . '" . $relativePath . "'";
        }

        return var_export($absolutePath, true);
    }
}
