<?php

namespace craft\cloud\composer;

use Composer\Composer;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;
use Composer\Script\ScriptEvents;

class PreloadPlugin implements PluginInterface, EventSubscriberInterface
{
    private Composer $composer;
    private IOInterface $io;
    private bool $done = false;

    public static function getSubscribedEvents(): array
    {
        return [
            ScriptEvents::POST_AUTOLOAD_DUMP => 'ensurePreloadFirst',
            ScriptEvents::POST_INSTALL_CMD => 'ensurePreloadFirst',
        ];
    }

    public function activate(Composer $composer, IOInterface $io): void
    {
        $this->composer = $composer;
        $this->io = $io;
    }

    public function deactivate(Composer $composer, IOInterface $io): void
    {
    }

    public function uninstall(Composer $composer, IOInterface $io): void
    {
    }

    public function ensurePreloadFirst(): void
    {
        if ($this->done) {
            return;
        }

        $this->done = true;

        $package = $this->composer->getRepositoryManager()
            ->getLocalRepository()
            ->findPackage('craftcms/cloud-ops', '*');

        if ($package === null) {
            $this->io->writeError('<info>craftcms/cloud-composer: cloud-ops not installed, skipping preload.</info>');
            return;
        }

        $installPath = $this->composer->getInstallationManager()->getInstallPath($package);
        $preloadFile = $installPath . '/preload.php';

        if (!file_exists($preloadFile)) {
            $this->io->writeError('<warning>craftcms/cloud-composer: preload.php not found at ' . $preloadFile . '</warning>');
            return;
        }

        $vendorDir = $this->composer->getConfig()->get('vendor-dir');
        $targetDir = $vendorDir . '/composer';
        $identifier = md5('craftcms/cloud-ops:preload.php');

        $this->rewriteAutoloadFiles($targetDir, $vendorDir, $identifier);
        $this->rewriteAutoloadStatic($targetDir, $identifier);

        $this->io->writeError('<info>craftcms/cloud-composer: preload.php moved to first position in autoload.</info>');
    }

    private function rewriteAutoloadFiles(string $targetDir, string $vendorDir, string $identifier): void
    {
        $autoloadFilesPath = $targetDir . '/autoload_files.php';

        if (!file_exists($autoloadFilesPath)) {
            return;
        }

        $files = include $autoloadFilesPath;

        if (!is_array($files) || !isset($files[$identifier])) {
            return;
        }

        $preloadEntry = [$identifier => $files[$identifier]];
        unset($files[$identifier]);
        $files = $preloadEntry + $files;

        $content = "<?php\n\n";
        $content .= "// autoload_files.php @generated by Composer\n\n";
        $content .= "\$vendorDir = dirname(__DIR__);\n";
        $content .= "\$baseDir = dirname(\$vendorDir);\n\n";
        $content .= "return array(\n";

        foreach ($files as $hash => $path) {
            $relativePath = $this->makeRelativePath($path, $vendorDir, dirname($vendorDir));
            $content .= "    '" . $hash . "' => " . $relativePath . ",\n";
        }

        $content .= ");\n";

        file_put_contents($autoloadFilesPath, $content);
    }

    private function rewriteAutoloadStatic(string $targetDir, string $identifier): void
    {
        $staticFilePath = $targetDir . '/autoload_static.php';

        if (!file_exists($staticFilePath)) {
            return;
        }

        $content = file_get_contents($staticFilePath);

        if (!preg_match('/public static \$files = array \(\n(.*?)\n    \);/s', $content, $matches)) {
            return;
        }

        $filesBlock = $matches[1];
        $lines = array_filter(explode("\n", $filesBlock), fn($line) => trim($line) !== '');

        $preloadLine = null;
        $otherLines = [];

        foreach ($lines as $line) {
            if (str_contains($line, "'" . $identifier . "'")) {
                $preloadLine = $line;
            } else {
                $otherLines[] = $line;
            }
        }

        if ($preloadLine === null) {
            return;
        }

        $newBlock = implode("\n", array_merge([$preloadLine], $otherLines));
        $content = preg_replace(
            '/public static \$files = array \(\n.*?\n    \);/s',
            "public static \$files = array (\n" . $newBlock . "\n    );",
            $content
        );

        file_put_contents($staticFilePath, $content);
    }

    private function makeRelativePath(string $absolutePath, string $vendorDir, string $baseDir): string
    {
        $absolutePath = str_replace('\\\\', '/', $absolutePath);
        $vendorDir = str_replace('\\\\', '/', $vendorDir);
        $baseDir = str_replace('\\\\', '/', $baseDir);

        if (str_starts_with($absolutePath, $vendorDir)) {
            return '$vendorDir . ' . var_export(substr($absolutePath, strlen($vendorDir)), true);
        }

        if (str_starts_with($absolutePath, $baseDir)) {
            return '$baseDir . ' . var_export(substr($absolutePath, strlen($baseDir)), true);
        }

        return var_export($absolutePath, true);
    }
}
