<?php

namespace craft\cloud\ops\composer;

use Composer\Composer;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;
use Composer\Script\Event;
use Composer\Script\ScriptEvents;

class Plugin implements PluginInterface, EventSubscriberInterface
{
    public function activate(Composer $composer, IOInterface $io): void
    {
    }

    public function deactivate(Composer $composer, IOInterface $io): void
    {
    }

    public function uninstall(Composer $composer, IOInterface $io): void
    {
    }

    public static function getSubscribedEvents(): array
    {
        return [
            ScriptEvents::POST_AUTOLOAD_DUMP => 'onPostAutoloadDump',
        ];
    }

    public function onPostAutoloadDump(Event $event): void
    {
        $vendorDir = $event->getComposer()->getConfig()->get('vendor-dir');
        $autoloadFilesPath = $vendorDir . '/composer/autoload_files.php';

        if (!file_exists($autoloadFilesPath)) {
            return;
        }

        $this->reorderAutoloadFiles($autoloadFilesPath, $event->getIO());
    }

    private function reorderAutoloadFiles(string $filePath, IOInterface $io): void
    {
        $files = require $filePath;

        if (!is_array($files)) {
            return;
        }

        $cloudOpsKey = null;
        $cloudOpsPath = null;

        foreach ($files as $key => $path) {
            if (str_contains($path, 'craftcms/cloud-ops')) {
                $cloudOpsKey = $key;
                $cloudOpsPath = $path;
                break;
            }
        }

        if ($cloudOpsKey === null) {
            return;
        }

        unset($files[$cloudOpsKey]);
        $files = [$cloudOpsKey => $cloudOpsPath] + $files;

        $content = "<?php\n\n// autoload_files.php @generated by Composer\n// cloud-ops reordered by craft\\cloud\\ops\\composer\\Plugin\n\n";
        $content .= '$vendorDir = dirname(__DIR__);' . "\n";
        $content .= '$baseDir = dirname($vendorDir);' . "\n\n";
        $content .= 'return ' . var_export($files, true) . ";\n";

        $content = str_replace("'" . dirname(dirname($filePath)) . "/", '$vendorDir . \'/', $content);
        $content = str_replace("'" . dirname(dirname(dirname($filePath))) . "/", '$baseDir . \'/', $content);

        file_put_contents($filePath, $content);

        $io->write('<info>cloud-ops:</info> Reordered autoload_files.php to prioritize craft_modify_app_config');
    }
}
