name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - 3.x
  pull_request:
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  code-quality:
    name: Code Quality
    uses: craftcms/.github/.github/workflows/code-quality.yml@v3
    with:
      node_version: '18'
      php_version: '8.3'
      jobs: '["ecs", "prettier"]'

  compatibility:
    name: Compatibility (Craft ${{ matrix.craft }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        craft:
          - '^4.6'
          - '^5'
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 33066:3306
        env:
          MYSQL_DATABASE: db
          MYSQL_USER: db
          MYSQL_PASSWORD: db
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -udb -pdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Resolve dependencies
        run: composer update "craftcms/cms:${{ matrix.craft }}" --with-all-dependencies --no-interaction --no-progress --prefer-dist

      - name: Prepare test environment
        run: composer test:init

      - name: Run PHPStan
        run: composer phpstan

      - name: Run unit tests
        run: composer test
