name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - 5.x
  pull_request:
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  code-quality:
    name: Code Quality
    uses: craftcms/.github/.github/workflows/code-quality.yml@v3
    with:
      node_version: '18'
      php_version: '8.3'
      jobs: '["ecs"]'

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Resolve dependencies
        run: composer update --with-all-dependencies --no-interaction --no-progress --prefer-dist --no-audit

      - name: Run PHPStan
        run: composer phpstan
